// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"PFMZ_ScreenResolution","status":true,"description":"[Version 1.0]","parameters":{"width":"1280","height":"720"}}
];
